### ISSUE TITLE
Add category field for extensions

### ISSUE THREAD

**Issue by kaklakariada** [exasol/extension-manager#100]
In order to improve usability of the UI we need to specify a category (e.g. `driver`, `virtual-schema`, ...) for extensions.

Precondition: https://github.com/exasol/extension-manager-interface/issues/42

```[tasklist]
### Tasks
- [ ] https://github.com/exasol/cloud-storage-extension/issues/251
- [ ] https://github.com/exasol/s3-document-files-virtual-schema/issues/120
- [ ] https://github.com/exasol/extension-manager-interface/issues/42
```

**Comment by ckunki** [comment]
Review result: Added 1-1 proposal/questions
