### ISSUE TITLE
Update registry to contain all versions of all extensions

### ISSUE THREAD

**Issue by kaklakariada** [exasol/extension-manager#179]
Currently the registry only contains the url of the latest version of each extension. This is a problem because if the required adapter is not available in BucketFS for the latest version, EM will hide the extension.

The proposed solution is to add a list of all versions for each extension:

```json
{
  "extensions": [
    {
      "id": "s3-document-files-virtual-schema",
      "url": "https://extensions-internal.exasol.com/com.exasol/s3-document-files-virtual-schema/3.0.3/s3-vs-extension.js"
      "versions": [
        {
          "version": "1.2.3",
          "extUrl": "https://extensions-internal.exasol.com/com.exasol/s3-document-files-virtual-schema/3.0.3/s3-vs-extension.js",
          "deprecated": false
          "lastest": true
        }
    ]
  }
]
}
```

This will allow the extension manager to find the latest version of an extension for which files are available in BucketFS. This means we can always add all the latest versions of extensions to the registry.

### Note
Extensions that don't need adapter files (e.g. Row-level-securty-lua) will automatically available in their latest version. It won't be possible to hide newer versions.

```[tasklist]
### Tasks
- [ ] Update registry parser to recognize new format (backwards compatible)
- [ ] Update registry-upload to generate new format
- [ ] Update EM to try loading versions of extensions until it finds one for which all required adapters are available in BucketFS.
```

**Comment by kaklakariada** [comment]
This project is deprecated and will be archived.
